### PR TITLE
minor improvements

### PR DESCRIPTION
**Pull request by agbondy**
Two improvements:
1. Windows has problems with very long path names. I added some workarounds to reduce crashing related to this. These workarounds only kick in on Windows if an error occurs during a save/load operation.
2. Minor change to the way kilosort import looks for the path name for the ap.bin file. It now prefers the path in the .prm file if one is provided, rather than the params.py file output by kilosort. The reasoning is that the params.py file only provides a local path, not a full path, requiring some error-prone reconstruction of the parent folder.

### CODE REVIEW

**Comment by aliddell** [comment]
Hey, thanks for the PR! I'm working on some bugs around history management, but once that's through I'll give this a close look.

**Review by aliddell — APPROVED** [review]

**Comment by aliddell** [comment]
OK some of the changes made here conflict with some changes I've made. In particular:
1. The `histFile` construct is deprecated (history is stored somewhat more compactly in the res file).
2. `loadFiles` is now a wrapper around `loadRes` and `loadBinaries`, so the change to loading the res file will go in `loadRes`

Your hacks put temporary files in the user's home dir. Is there a good reason for there in particular, or would it suffice to use Matlab's built in tempfile handling?

**Comment by agbondy** [comment]
Hi Alan. However you want to handle the merge is fine. Using Matlab's built in tempfile handling sounds like an improvement. Also, if you'd rather just reject the PR I can try to work on a version that is compatible with your recent changes.

**Comment by aliddell** [comment]
No, it's pretty simple for me to do. I'll take care of the tempfile stuff too.

**Comment by agbondy** [comment]
Hey @aliddell  -- I see you've made a large number of commits recently. Is "master" in a state where you'd recommend people try it out or are you still testing your recent changes? Were these mainly improvements or bug fixes?

**Comment by aliddell** [comment]
They're essentially a large bugfix around that perennial problem of history management, but a fair amount of new code is actually unit tests, so I'd say it's pretty safe.

**Comment by agbondy** [comment]
OK thanks. I didn't realize there were bugs in the history management. Should we treat the history files are unusable up until the current version?

**Comment by aliddell** [comment]
No, the history files are fine but there were some post-revert hooks that were not firing (but you still end up with the correct spike table). The big change is that in order to make things simpler and more compact, the history files are being deprecated, the operations have their own well-defined formats in the history struct/side effects in the code, and reverting doesn't force a recompute of everything anymore, just affected unit metadata.

**Comment by agbondy** [comment]
Got it. Thanks.

**Pull request merged**
